# PCA

In [1]:
import sys

sys.path.append("../..")

In [2]:
from mlalgo.utils.helper_functions import covariance_matrix

In [3]:
import numpy as np

In [4]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.cov(X)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
covariance_matrix(X, rowvar=True)

array([[ 1.5,  0. , -1.5],
       [ 0. ,  0. ,  0. ],
       [-1.5,  0. ,  1.5]])

In [14]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x_mean = np.mean(X, axis=1)

In [15]:
(9+6+3)/3

6.0

In [22]:
x_mean.reshape(3, 1)

array([[2.],
       [5.],
       [8.]])

In [24]:
Z = X - x_mean.reshape(3, 1)

In [26]:
Z @ Z.T / 2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[11.66666667,  2.66666667, -6.33333333],
       [ 2.66666667,  2.66666667,  2.66666667],
       [-6.33333333,  2.66666667, 11.66666667]])

In [7]:
covariance_matrix(X)

array([[ 13.5,   0. , -13.5],
       [  0. ,   0. ,   0. ],
       [-13.5,   0. ,  13.5]])

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from mlalgo.dimensionality_reduction.pca import PCA